### ISSUE TITLE
[COMPONENT] Tabs

### ISSUE THREAD

**Issue by michalgren** [Selleo/design-system#25]
We need tabs to be designed

- [x] Designs https://www.figma.com/file/aAZNLti1x7RHcKO2aaVdyh/Selleo-Design-System?node-id=2430%3A4658&t=kO4aJ2U5f5S3KHJz-0
- [x] Implementation

New tabs are designed so we can proceed with the implementation.
- Both dark & light mode are designed so should be implemented
- Each state should be shown in the docs (default & active)
- Icon edge case should be shown

Notes
- [Figma Design](https://www.figma.com/file/aAZNLti1x7RHcKO2aaVdyh/Selleo-Design-System?node-id=2430%3A4658&t=kO4aJ2U5f5S3KHJz-0)

**Comment by k1eu** [comment]
First step is to get the designs ready @qbart, do we have any free designer?

**Comment by qbart** [comment]
not right now, but let's have it open

**Comment by k1eu** [comment]
Tabs are now designed so we can proceed with the implementation, modifying the main desc
