### ISSUE TITLE
Create Icon list

### ISSUE THREAD

**Issue by k1eu** [Selleo/design-system#82]
We'd like to have a icon list page displaying all the icons we use within our apps. For now we can move only the icons we're using in a project. Since we don't have much we'd do it all localy, without any API integration. 

The goal is to have something similar to this:
https://tabler-icons.io/

- [x] Create a page called Icons
- [x] It should be a React/Preact Island in Astro
- [x] NEW! When clicking on the icon we should display Modal with Icon, name and ability to copy

**Comment by PoslinskiNet** [comment]
@k1eu I've edited the description - search is not needed for now. Just a listing as a grid, with ability to easy copy SVG code of each icon and or save as an image.

**Comment by k1eu** [comment]
@PoslinskiNet sounds good to me
@DawidHaratyk check out
